[versions]
compose_bom = "2023.03.00"
compose_version = "1.4.0"

[libraries]
compose-bom = { group = "androidx.compose", name = "compose_Bom", version.ref = "compose_bom" }
compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref ="compose_version" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref ="compose_version" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref ="compose_version" }
compose-ui-toolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref ="compose_version" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref ="compose_version" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref ="compose_version" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref ="compose_version" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref ="compose_version" }
compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref ="compose_version" }

[bundles]
compose = [
    "compose-animation",
    "compose-foundation",
    "compose-ui",
    "compose-ui-toolingPreview",
    "compose-ui-tooling",
    "compose-runtime",
    "compose-runtime-livedata",
    "compose-material",
    "compose-material-iconsExtended"]
[plugins]