[versions]
composeBom = "2023.03.00"
androidx_Compose = "1.4.0"
androidx_ComposeCompiler = "1.4.4"
androidxCore = "1.9.0"
androidxAppcompat = "1.6.1"
kotlinxSerialization = "1.4.1"
kotlinxCoroutines = "1.6.4"
kotlinxCoroutinesAndroid = "1.6.4"
andoidxWindow = "1.0.0"
andoidxWork = "2.8.0"
andoidxNavigationCompose = "2.5.3"
andoidxLifecycle = "2.5.1"
androidxActivityCompose = "1.6.1"
androidxHiltWork = "1.0.0"
andoidxDatastorePreferences = "1.0.0"
accompanistNavigationAnimation = "0.28.0"
hiltNavigationCompose = "1.0.0"
hiltAndroid = "2.44.0"
timberLogger = "5.0.1"

[libraries]
compose-bom = { group = "androidx.compose", name = "compose_Bom", version.ref = "composeBom" }
compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "androidx_Compose" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidx_Compose" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidx_Compose" }
compose-ui-toolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidx_Compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidx_Compose" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "androidx_Compose" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "androidx_Compose" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "androidx_Compose" }
compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "androidx_Compose" }
androidx-Core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-AppCompat = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-Window = { group = "androidx.window", name = "window", version.ref = "andoidxWindow" }
androidx-Work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "andoidxWork" }
androidx-NavigationCompose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "andoidxNavigationCompose" }
androidx-LifecycleRuntimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "andoidxLifecycle" }
androidx-LifecycleViewModelKtx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "andoidxLifecycle" }
androidx-LifecycleLiveDataKtx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "andoidxLifecycle" }
androidx-LifecycleComposeRuntime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "andoidxLifecycle" }
androidx-LifecycleViewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "andoidxLifecycle" }
androidx-ActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityCompose" }
androidx-Datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "andoidxDatastorePreferences" }
androidx-HiltWork = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidxHiltWork" }
androidx-KaptCompiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidxHiltWork" }
kotlix-Serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlix-CoroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlix-CoroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
accompanist_NavigationAnimation = { group = "com.google.accompanist", name = "accompanist-navigation-animation", version.ref = "accompanistNavigationAnimation" }
timberLogger = { group = "com.jakewharton.timber", name = "timber", version.ref = "timberLogger" }
hilt_NavigationCompose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt_Android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroid" }
hilt_KaptCompiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltAndroid" }


[bundles]
compose = [
    "compose-animation",
    "compose-foundation",
    "compose-ui",
    "compose-ui-toolingPreview",
    "compose-ui-tooling",
    "compose-runtime",
    "compose-runtime-livedata",
    "compose-material",
    "compose-material-iconsExtended"]
[plugins]